- name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          sdk-channel: release
          # On force le clean AVANT de compiler
          ufbt-args: "clean" 

      - name: Compile FAP
        run: ufbt
