name: "Build ProtoPirate Full Edition"
on: [push, workflow_dispatch]

jobs:
  build-fap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ufbt
        run: pip install ufbt

      - name: Full Clean and Rebuild
        run: |
          ufbt clean          # Nettoie le SDK
          ufbt -c             # Nettoie spécifiquement les fichiers de ton APP
          ufbt                # Recompile tout de zéro
        
      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ProtoPirate-fap
          path: "./dist/*.fap"
